name: CI/CD Pipeline

on:
  push:
    branches:
      - preview

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        ls -la
        npm install

    - name: Build project
      run: |
        ng build
        touch .nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAGES_TOKEN }}
        publish_dir: dist/angular-tour-of-heroes/browser
        publish_branch: gh-pages  

          
          
          
